[toolchain.node]
version = "22.12.0"

[toolchain.pnpm]
version = "9.15.0"

[toolchain.mutagen]
version = "0.18.1"

[mutagen]
[[mutagen.sync]]
name = "shared"
target = "docker://ebdev@example-sync-target-1/var/www/shared"
directory = "./shared"
mode = "two-way"
stage = 0
ignore = [".git", "node_modules"]
