[package]
name = "ebdev-toolchain-ebdev"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
reqwest.workspace = true
futures-util.workspace = true
thiserror.workspace = true
