[package]
name = "ebdev-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
ebdev-toolchain-deno = { path = "../toolchain_deno" }
tokio.workspace = true
