[workspace]
resolver = "2"
members = [
    "crates/toolchain",
    "crates/cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["easybill GmbH"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
