[package]
name = "ebdev-mutagen-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
toml.workspace = true
thiserror.workspace = true
walkdir.workspace = true
crc32fast.workspace = true
