[mutagen]
[[mutagen.sync]]
name = "frontend"
target = "docker://ebdev@example-sync-target-1/var/www/frontend"
mode = "two-way"
stage = 1
ignore = [".git", "node_modules", "dist", ".next"]

[mutagen.sync.polling]
enabled = true
interval = 5
